version: '3'
services:
  easy-gtts-api:
    image: docker.pkg.github.com/regulad/easy-gtts-api/easy-gtts-api:latest
    ports:
      - 8080:8080/tcp
    volumes:
      - config:/app/config
volumes:
  config:
